/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const materialProps = {
    thickness: 5,
    roughness: 0,
    clearcoat: 3,
    clearcoatRoughness: 0,
    transmission: 0.7,
    ior: 1.5,
    envMapIntensity: 0,
    color: "#9090e8",
    attenuationDistance: 0,
    normalScale: 0.5,
  };

  const group = useRef();
  const { nodes, materials } = useGLTF("models/links/discord.gltf");
  return (
    <mesh
      ref={group}
      scale={0.15}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      {...props}
      geometry={nodes.Plane.geometry}
      material={nodes.Plane.material}
    >
      <meshPhysicalMaterial {...materialProps} />
    </mesh>
  );
}

useGLTF.preload("/discord.gltf");
