/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/links/twitter.gltf");
  return (
    <mesh
      ref={group}
      scale={0.14}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      {...props}
      geometry={nodes.Plane.geometry}
      material={nodes.Plane.material}
    >
      <meshBasicMaterial color={"#1DA1F2"} />
    </mesh>
  );
}

useGLTF.preload("/twitter.gltf");
