/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/discord.gltf");
  return (
    <group
      ref={group}
      scale={0.1}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <mesh
        {...props}
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
      />
    </group>
  );
}

useGLTF.preload("/discord.gltf");
