/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./lora.gltf");
  materials.wireframe = true;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry}>
        <meshBasicMaterial attach="material" color="white" wireframe />
      </mesh>
    </group>
  );
}

useGLTF.preload("/lora.gltf");
