/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";

export default function Model({ ready, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./lora.gltf");
  materials.wireframe = true;

  useEffect(() => {
    group.current.position.set(0, -20, 0);
  }, []);

  // Lerp stuff shouldnt be here
  useFrame(() => {
    if (ready) {
      group.current.position.lerp(new THREE.Vector3(0, -6, -8), 0.02);
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry}>
        <meshBasicMaterial attach="material" color="white" wireframe />
      </mesh>
    </group>
  );
}

useGLTF.preload("/lora.gltf");
